Update NN_Obj_Det Part2.py
Getting the following runtime error:

Traceback (most recent call last):
  File "c:\Users\Yoni Ben-Zvi\VSCodeProjects\CV3\NN_Obj_Det Part2.py", line 263, in <module>
    train_model(model, train_loader, val_loader, num_epochs=20, learning_rate=1e-4)
  File "c:\Users\Yoni Ben-Zvi\VSCodeProjects\CV3\NN_Obj_Det Part2.py", line 210, in train_model
    for images, targets in train_loader:
                           ^^^^^^^^^^^^
  File "C:\Users\Yoni Ben-Zvi\VSCodeProjects\Lib\site-packages\torch\utils\data\dataloader.py", line 708, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni Ben-Zvi\VSCodeProjects\Lib\site-packages\torch\utils\data\dataloader.py", line 1480, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni Ben-Zvi\VSCodeProjects\Lib\site-packages\torch\utils\data\dataloader.py", line 1505, in _process_data
    data.reraise()
  File "C:\Users\Yoni Ben-Zvi\VSCodeProjects\Lib\site-packages\torch\_utils.py", line 733, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Yoni Ben-Zvi\VSCodeProjects\Lib\site-packages\torch\utils\data\_utils\worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni Ben-Zvi\VSCodeProjects\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 55, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni Ben-Zvi\VSCodeProjects\Lib\site-packages\torch\utils\data\_utils\collate.py", line 398, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni Ben-Zvi\VSCodeProjects\Lib\site-packages\torch\utils\data\_utils\collate.py", line 212, in collate
    collate(samples, collate_fn_map=collate_fn_map)
  File "C:\Users\Yoni Ben-Zvi\VSCodeProjects\Lib\site-packages\torch\utils\data\_utils\collate.py", line 155, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yoni Ben-Zvi\VSCodeProjects\Lib\site-packages\torch\utils\data\_utils\collate.py", line 272, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects each tensor to be equal size, but got [841] at entry 0 and [6475] at entry 1